@echo off
echo Starting development server...
start "Next.js Dev Server" cmd /k "npm run dev"
echo.
echo Waiting for server to start...
timeout /t 5 /nobreak
echo.
echo Running API tests...
node test-availability-api.js
echo.
echo Press any key to exit...
pause
